### ISSUE TITLE
ESLify Everything stops working in some cases (Possibly Mutagen issue)

### ISSUE THREAD

**Issue by MoonbeamLure** [Michael-wigontherun/ESLifyEverything#2] opened 2022-10-21 23:16 UTC
Hi there. I found a bug within Mutagen (I think) that causes it to crash when it finds a subrecord with a datasize greater than I'd assume 65535.  This happens during the RunSubPluginCompaction stage

I posted the link over here, just in case:  https://github.com/Mutagen-Modding/Mutagen/issues/382

I'm not sure if there's a work around other than turning off RunSubPluginCompaction and ensuring that you have all of the plugins you need adjusted present before you start ESLing. It's probably not going to be ran into that often because I don't think that many subrecords get to a data-size that big anyway.

**Comment by Michael-wigontherun** [comment] 2022-10-22 07:16
What did you even ESLify to need to edit the esm?

I need the entire error in order to find a fix I have no clue where that error you cut out the line report.

**Comment by MoonbeamLure** [comment] 2022-10-22 08:07
> What did you even ESLify to need to edit the esm?

> I need the entire error in order to find a fix I have no clue where that error you cut out the line report.

Sorry, I really need to remember to give you the full log and not just the error.

I wasn't trying it for actual in-game purposes, mostly to see what'd happen if I tried to ESLify an ESM in terms of functionality if I used the RunSubPluginCompaction thingy and the SexLab mods are the ones I know that have the most interconnectedness with each other in terms of GetFormFromFile calls. I'm mostly testing to see whether or not RunSubPluginCompaction will reliably make it so masters with lots of sub-plugins will be able to be ESLified without ruining anything even if you add a new mod later. So far, so good, except for the problem with Devious Devices - Expansion.esm as I noted above. SexLab is considered a parent to Devious Devices. 

Log found here: https://pastebin.com/HeB2cTap
Steps to recreate:

1. Compact and ESL flag Sexlab.esm. All of the loaded plugins (assuming only SexLab and Devious Devices are loaded) should become highlighted.
2. Compact and ESL flag Devious Devices - Assets.esm. Save.
3. Run through the whole process of ESlifying.
4. Do PluginSubCompaction.  It fails when it tries to read Devious Devices - Expansion's quest subheader at ID zadxQuest (00CA01:Devious Devices - Expansion.esm<Quest>)

If you check at the quest subheader 00CA01 in xEdit, you see the data size is 72,000 and some change because of the number of scripts associated with this quest. I'm assuming that most of the scripts are connected to the various armors so that they will execute their intended effects whatever they may be. If you deleted enough of the subheader's information to become under 65,000 data size, ESLify Everything finishes reading. 

This is the only master I've found this error on, and I think it's because the programmers of Mutagen didn't foresee a situation where a single record in a esp or esm has such a large size?

**Comment by Michael-wigontherun** [comment] 2022-10-22 08:19
That still isn't what I need. I need the lines where it returns an overflow exception. The image you sent on the Mutagen post has the actual line reports cut off. I can't find a fix without knowing were the issue is.

**Comment by Michael-wigontherun** [comment] 2022-10-22 18:50
Can you replicate the exception using this build.
[https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/A3.3.0](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/A3.3.0)
and can you enable Dev Logging by adding the DevAppSettings.json to your folder with ESLifyEverything.exe. and setting the setting to true.

**Comment by MoonbeamLure** [comment] 2022-10-22 21:14
Sorry, I don't see a DevAppSettings.json in the source code or the build folder.

**Comment by Michael-wigontherun** [comment] 2022-10-22 21:17
Use the ESLifyCreateJson. I didn't include it because its really only meant for me to debug and I don't want normal people complaining about too much logging information. In hindsight I could have just uploaded with the prerelease.

**Comment by MoonbeamLure** [comment] 2022-10-22 21:33
Okay, I ran it a few times while fiddling with the DevAppSettings settings and the log ended up being very similar or the same. I didn't see a Dev log so hopefully this is the log you were looking for. The program still crashed at the same spot with the same hex address.

https://pastebin.com/P8diRRLB

**Comment by Michael-wigontherun** [comment] 2022-10-22 21:58
Try this again, This is the only thing I can try if this doesn't work then it has to be fixed on [Noggog](https://github.com/Noggog)'s end.

[https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/A3.3.0](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/A3.3.0)

**Comment by MoonbeamLure** [comment] 2022-10-22 22:02
Yea, looks like it's still busted. Sad :(

Log just in case: https://pastebin.com/Qc6YXmAv

It seems to work most of the time, though. This has been the only file I've had trouble with in all of the random array of testing I've done.

**Closed as completed** 2023-01-17 14:52 UTC
